[package]
name = "add_macro"
description = "This crate adds the some useful macros for easily work"
version = "0.1.0"
edition = "2021"
authors = ["Draken inc. <t.me/drakeninc>"]
license = "MIT"
repository = "https://github.com/draken/add_macro"

[dependencies]
display_derive = { version = "0.0.0", path = "lib/display_derive" }
thiserror = "1.0.57"
